// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace hd_sentry {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class HdSentryHostApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};



class PigeonInternalCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;
 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;
};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class HdSentryHostApi {
 public:
  HdSentryHostApi(const HdSentryHostApi&) = delete;
  HdSentryHostApi& operator=(const HdSentryHostApi&) = delete;
  virtual ~HdSentryHostApi() {}
  // Installs native crash handlers. Call as early as possible (e.g. before [runApp]).
  virtual std::optional<FlutterError> Initialize() = 0;
  // Absolute path to the directory where crash reports are stored.
  virtual ErrorOr<std::string> GetCrashDirectory() = 0;
  // File names (not full paths) of pending crash reports.
  virtual ErrorOr<flutter::EncodableList> ListCrashFileNames() = 0;
  // Full text content of a crash report file.
  virtual ErrorOr<std::string> ReadCrashFile(const std::string& file_name) = 0;
  // Deletes a single crash report. Returns true if the file existed.
  virtual ErrorOr<bool> DeleteCrashFile(const std::string& file_name) = 0;
  // Deletes all crash reports in [getCrashDirectory].
  virtual std::optional<FlutterError> ClearAllCrashFiles() = 0;
  // Captures an exception.
  virtual std::optional<FlutterError> CaptureException(
    const std::string& message,
    const std::string* stack_trace) = 0;

  // The codec used by HdSentryHostApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `HdSentryHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    HdSentryHostApi* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    HdSentryHostApi* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  HdSentryHostApi() = default;
};
}  // namespace hd_sentry
#endif  // PIGEON_MESSAGES_G_H_
