// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class MessagesPigeonCodecReader: FlutterStandardReader {
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol HdSentryHostApi {
  /// Installs native crash handlers. Call as early as possible (e.g. before [runApp]).
  func initialize() throws
  /// Absolute path to the directory where crash reports are stored.
  func getCrashDirectory() throws -> String
  /// File names (not full paths) of pending crash reports.
  func listCrashFileNames() throws -> [String]
  /// Full text content of a crash report file.
  func readCrashFile(fileName: String) throws -> String
  /// Deletes a single crash report. Returns true if the file existed.
  func deleteCrashFile(fileName: String) throws -> Bool
  /// Deletes all crash reports in [getCrashDirectory].
  func clearAllCrashFiles() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class HdSentryHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `HdSentryHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: HdSentryHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Installs native crash handlers. Call as early as possible (e.g. before [runApp]).
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hd_sentry.HdSentryHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { _, reply in
        do {
          try api.initialize()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    /// Absolute path to the directory where crash reports are stored.
    let getCrashDirectoryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hd_sentry.HdSentryHostApi.getCrashDirectory\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCrashDirectoryChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getCrashDirectory()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getCrashDirectoryChannel.setMessageHandler(nil)
    }
    /// File names (not full paths) of pending crash reports.
    let listCrashFileNamesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hd_sentry.HdSentryHostApi.listCrashFileNames\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      listCrashFileNamesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.listCrashFileNames()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      listCrashFileNamesChannel.setMessageHandler(nil)
    }
    /// Full text content of a crash report file.
    let readCrashFileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hd_sentry.HdSentryHostApi.readCrashFile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readCrashFileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let fileNameArg = args[0] as! String
        do {
          let result = try api.readCrashFile(fileName: fileNameArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      readCrashFileChannel.setMessageHandler(nil)
    }
    /// Deletes a single crash report. Returns true if the file existed.
    let deleteCrashFileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hd_sentry.HdSentryHostApi.deleteCrashFile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteCrashFileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let fileNameArg = args[0] as! String
        do {
          let result = try api.deleteCrashFile(fileName: fileNameArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      deleteCrashFileChannel.setMessageHandler(nil)
    }
    /// Deletes all crash reports in [getCrashDirectory].
    let clearAllCrashFilesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hd_sentry.HdSentryHostApi.clearAllCrashFiles\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearAllCrashFilesChannel.setMessageHandler { _, reply in
        do {
          try api.clearAllCrashFiles()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearAllCrashFilesChannel.setMessageHandler(nil)
    }
  }
}
