// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *nullGetMessagesCodec(void);

@protocol HdSentryHostApi
/// Installs native crash handlers. Call as early as possible (e.g. before [runApp]).
- (void)initializeWithError:(FlutterError *_Nullable *_Nonnull)error;
/// Absolute path to the directory where crash reports are stored.
///
/// @return `nil` only when `error != nil`.
- (nullable NSString *)getCrashDirectoryWithError:(FlutterError *_Nullable *_Nonnull)error;
/// File names (not full paths) of pending crash reports.
///
/// @return `nil` only when `error != nil`.
- (nullable NSArray<NSString *> *)listCrashFileNamesWithError:(FlutterError *_Nullable *_Nonnull)error;
/// Full text content of a crash report file.
///
/// @return `nil` only when `error != nil`.
- (nullable NSString *)readCrashFileFileName:(NSString *)fileName error:(FlutterError *_Nullable *_Nonnull)error;
/// Deletes a single crash report. Returns true if the file existed.
///
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)deleteCrashFileFileName:(NSString *)fileName error:(FlutterError *_Nullable *_Nonnull)error;
/// Deletes all crash reports in [getCrashDirectory].
- (void)clearAllCrashFilesWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpHdSentryHostApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<HdSentryHostApi> *_Nullable api);

extern void SetUpHdSentryHostApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<HdSentryHostApi> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
