// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#include "messages.g.h"

struct _hd_sentryMessageCodec {
  FlStandardMessageCodec parent_instance;

};

G_DEFINE_TYPE(hd_sentryMessageCodec, hd_sentry_message_codec, fl_standard_message_codec_get_type())


static gboolean hd_sentry_message_codec_write_value(FlStandardMessageCodec* codec, GByteArray* buffer, FlValue* value, GError** error) {
  if (fl_value_get_type(value) == FL_VALUE_TYPE_CUSTOM) {
    switch (fl_value_get_custom_type(value)) {
    }
  }

  return FL_STANDARD_MESSAGE_CODEC_CLASS(hd_sentry_message_codec_parent_class)->write_value(codec, buffer, value, error);
}

static FlValue* hd_sentry_message_codec_read_value_of_type(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, int type, GError** error) {
  switch (type) {
    default:
      return FL_STANDARD_MESSAGE_CODEC_CLASS(hd_sentry_message_codec_parent_class)->read_value_of_type(codec, buffer, offset, type, error);
  }
}

static void hd_sentry_message_codec_init(hd_sentryMessageCodec* self) {
}

static void hd_sentry_message_codec_class_init(hd_sentryMessageCodecClass* klass) {
  FL_STANDARD_MESSAGE_CODEC_CLASS(klass)->write_value = hd_sentry_message_codec_write_value;
  FL_STANDARD_MESSAGE_CODEC_CLASS(klass)->read_value_of_type = hd_sentry_message_codec_read_value_of_type;
}

static hd_sentryMessageCodec* hd_sentry_message_codec_new() {
  hd_sentryMessageCodec* self = HD_SENTRY_MESSAGE_CODEC(g_object_new(hd_sentry_message_codec_get_type(), nullptr));
  return self;
}

struct _hd_sentryHdSentryHostApiInitializeResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(hd_sentryHdSentryHostApiInitializeResponse, hd_sentry_hd_sentry_host_api_initialize_response, G_TYPE_OBJECT)

static void hd_sentry_hd_sentry_host_api_initialize_response_dispose(GObject* object) {
  hd_sentryHdSentryHostApiInitializeResponse* self = HD_SENTRY_HD_SENTRY_HOST_API_INITIALIZE_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(hd_sentry_hd_sentry_host_api_initialize_response_parent_class)->dispose(object);
}

static void hd_sentry_hd_sentry_host_api_initialize_response_init(hd_sentryHdSentryHostApiInitializeResponse* self) {
}

static void hd_sentry_hd_sentry_host_api_initialize_response_class_init(hd_sentryHdSentryHostApiInitializeResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = hd_sentry_hd_sentry_host_api_initialize_response_dispose;
}

hd_sentryHdSentryHostApiInitializeResponse* hd_sentry_hd_sentry_host_api_initialize_response_new() {
  hd_sentryHdSentryHostApiInitializeResponse* self = HD_SENTRY_HD_SENTRY_HOST_API_INITIALIZE_RESPONSE(g_object_new(hd_sentry_hd_sentry_host_api_initialize_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_null());
  return self;
}

hd_sentryHdSentryHostApiInitializeResponse* hd_sentry_hd_sentry_host_api_initialize_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  hd_sentryHdSentryHostApiInitializeResponse* self = HD_SENTRY_HD_SENTRY_HOST_API_INITIALIZE_RESPONSE(g_object_new(hd_sentry_hd_sentry_host_api_initialize_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _hd_sentryHdSentryHostApiGetCrashDirectoryResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(hd_sentryHdSentryHostApiGetCrashDirectoryResponse, hd_sentry_hd_sentry_host_api_get_crash_directory_response, G_TYPE_OBJECT)

static void hd_sentry_hd_sentry_host_api_get_crash_directory_response_dispose(GObject* object) {
  hd_sentryHdSentryHostApiGetCrashDirectoryResponse* self = HD_SENTRY_HD_SENTRY_HOST_API_GET_CRASH_DIRECTORY_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(hd_sentry_hd_sentry_host_api_get_crash_directory_response_parent_class)->dispose(object);
}

static void hd_sentry_hd_sentry_host_api_get_crash_directory_response_init(hd_sentryHdSentryHostApiGetCrashDirectoryResponse* self) {
}

static void hd_sentry_hd_sentry_host_api_get_crash_directory_response_class_init(hd_sentryHdSentryHostApiGetCrashDirectoryResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = hd_sentry_hd_sentry_host_api_get_crash_directory_response_dispose;
}

hd_sentryHdSentryHostApiGetCrashDirectoryResponse* hd_sentry_hd_sentry_host_api_get_crash_directory_response_new(const gchar* return_value) {
  hd_sentryHdSentryHostApiGetCrashDirectoryResponse* self = HD_SENTRY_HD_SENTRY_HOST_API_GET_CRASH_DIRECTORY_RESPONSE(g_object_new(hd_sentry_hd_sentry_host_api_get_crash_directory_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(return_value));
  return self;
}

hd_sentryHdSentryHostApiGetCrashDirectoryResponse* hd_sentry_hd_sentry_host_api_get_crash_directory_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  hd_sentryHdSentryHostApiGetCrashDirectoryResponse* self = HD_SENTRY_HD_SENTRY_HOST_API_GET_CRASH_DIRECTORY_RESPONSE(g_object_new(hd_sentry_hd_sentry_host_api_get_crash_directory_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _hd_sentryHdSentryHostApiListCrashFileNamesResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(hd_sentryHdSentryHostApiListCrashFileNamesResponse, hd_sentry_hd_sentry_host_api_list_crash_file_names_response, G_TYPE_OBJECT)

static void hd_sentry_hd_sentry_host_api_list_crash_file_names_response_dispose(GObject* object) {
  hd_sentryHdSentryHostApiListCrashFileNamesResponse* self = HD_SENTRY_HD_SENTRY_HOST_API_LIST_CRASH_FILE_NAMES_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(hd_sentry_hd_sentry_host_api_list_crash_file_names_response_parent_class)->dispose(object);
}

static void hd_sentry_hd_sentry_host_api_list_crash_file_names_response_init(hd_sentryHdSentryHostApiListCrashFileNamesResponse* self) {
}

static void hd_sentry_hd_sentry_host_api_list_crash_file_names_response_class_init(hd_sentryHdSentryHostApiListCrashFileNamesResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = hd_sentry_hd_sentry_host_api_list_crash_file_names_response_dispose;
}

hd_sentryHdSentryHostApiListCrashFileNamesResponse* hd_sentry_hd_sentry_host_api_list_crash_file_names_response_new(FlValue* return_value) {
  hd_sentryHdSentryHostApiListCrashFileNamesResponse* self = HD_SENTRY_HD_SENTRY_HOST_API_LIST_CRASH_FILE_NAMES_RESPONSE(g_object_new(hd_sentry_hd_sentry_host_api_list_crash_file_names_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_ref(return_value));
  return self;
}

hd_sentryHdSentryHostApiListCrashFileNamesResponse* hd_sentry_hd_sentry_host_api_list_crash_file_names_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  hd_sentryHdSentryHostApiListCrashFileNamesResponse* self = HD_SENTRY_HD_SENTRY_HOST_API_LIST_CRASH_FILE_NAMES_RESPONSE(g_object_new(hd_sentry_hd_sentry_host_api_list_crash_file_names_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _hd_sentryHdSentryHostApiReadCrashFileResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(hd_sentryHdSentryHostApiReadCrashFileResponse, hd_sentry_hd_sentry_host_api_read_crash_file_response, G_TYPE_OBJECT)

static void hd_sentry_hd_sentry_host_api_read_crash_file_response_dispose(GObject* object) {
  hd_sentryHdSentryHostApiReadCrashFileResponse* self = HD_SENTRY_HD_SENTRY_HOST_API_READ_CRASH_FILE_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(hd_sentry_hd_sentry_host_api_read_crash_file_response_parent_class)->dispose(object);
}

static void hd_sentry_hd_sentry_host_api_read_crash_file_response_init(hd_sentryHdSentryHostApiReadCrashFileResponse* self) {
}

static void hd_sentry_hd_sentry_host_api_read_crash_file_response_class_init(hd_sentryHdSentryHostApiReadCrashFileResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = hd_sentry_hd_sentry_host_api_read_crash_file_response_dispose;
}

hd_sentryHdSentryHostApiReadCrashFileResponse* hd_sentry_hd_sentry_host_api_read_crash_file_response_new(const gchar* return_value) {
  hd_sentryHdSentryHostApiReadCrashFileResponse* self = HD_SENTRY_HD_SENTRY_HOST_API_READ_CRASH_FILE_RESPONSE(g_object_new(hd_sentry_hd_sentry_host_api_read_crash_file_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(return_value));
  return self;
}

hd_sentryHdSentryHostApiReadCrashFileResponse* hd_sentry_hd_sentry_host_api_read_crash_file_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  hd_sentryHdSentryHostApiReadCrashFileResponse* self = HD_SENTRY_HD_SENTRY_HOST_API_READ_CRASH_FILE_RESPONSE(g_object_new(hd_sentry_hd_sentry_host_api_read_crash_file_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _hd_sentryHdSentryHostApiDeleteCrashFileResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(hd_sentryHdSentryHostApiDeleteCrashFileResponse, hd_sentry_hd_sentry_host_api_delete_crash_file_response, G_TYPE_OBJECT)

static void hd_sentry_hd_sentry_host_api_delete_crash_file_response_dispose(GObject* object) {
  hd_sentryHdSentryHostApiDeleteCrashFileResponse* self = HD_SENTRY_HD_SENTRY_HOST_API_DELETE_CRASH_FILE_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(hd_sentry_hd_sentry_host_api_delete_crash_file_response_parent_class)->dispose(object);
}

static void hd_sentry_hd_sentry_host_api_delete_crash_file_response_init(hd_sentryHdSentryHostApiDeleteCrashFileResponse* self) {
}

static void hd_sentry_hd_sentry_host_api_delete_crash_file_response_class_init(hd_sentryHdSentryHostApiDeleteCrashFileResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = hd_sentry_hd_sentry_host_api_delete_crash_file_response_dispose;
}

hd_sentryHdSentryHostApiDeleteCrashFileResponse* hd_sentry_hd_sentry_host_api_delete_crash_file_response_new(gboolean return_value) {
  hd_sentryHdSentryHostApiDeleteCrashFileResponse* self = HD_SENTRY_HD_SENTRY_HOST_API_DELETE_CRASH_FILE_RESPONSE(g_object_new(hd_sentry_hd_sentry_host_api_delete_crash_file_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_bool(return_value));
  return self;
}

hd_sentryHdSentryHostApiDeleteCrashFileResponse* hd_sentry_hd_sentry_host_api_delete_crash_file_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  hd_sentryHdSentryHostApiDeleteCrashFileResponse* self = HD_SENTRY_HD_SENTRY_HOST_API_DELETE_CRASH_FILE_RESPONSE(g_object_new(hd_sentry_hd_sentry_host_api_delete_crash_file_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _hd_sentryHdSentryHostApiClearAllCrashFilesResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(hd_sentryHdSentryHostApiClearAllCrashFilesResponse, hd_sentry_hd_sentry_host_api_clear_all_crash_files_response, G_TYPE_OBJECT)

static void hd_sentry_hd_sentry_host_api_clear_all_crash_files_response_dispose(GObject* object) {
  hd_sentryHdSentryHostApiClearAllCrashFilesResponse* self = HD_SENTRY_HD_SENTRY_HOST_API_CLEAR_ALL_CRASH_FILES_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(hd_sentry_hd_sentry_host_api_clear_all_crash_files_response_parent_class)->dispose(object);
}

static void hd_sentry_hd_sentry_host_api_clear_all_crash_files_response_init(hd_sentryHdSentryHostApiClearAllCrashFilesResponse* self) {
}

static void hd_sentry_hd_sentry_host_api_clear_all_crash_files_response_class_init(hd_sentryHdSentryHostApiClearAllCrashFilesResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = hd_sentry_hd_sentry_host_api_clear_all_crash_files_response_dispose;
}

hd_sentryHdSentryHostApiClearAllCrashFilesResponse* hd_sentry_hd_sentry_host_api_clear_all_crash_files_response_new() {
  hd_sentryHdSentryHostApiClearAllCrashFilesResponse* self = HD_SENTRY_HD_SENTRY_HOST_API_CLEAR_ALL_CRASH_FILES_RESPONSE(g_object_new(hd_sentry_hd_sentry_host_api_clear_all_crash_files_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_null());
  return self;
}

hd_sentryHdSentryHostApiClearAllCrashFilesResponse* hd_sentry_hd_sentry_host_api_clear_all_crash_files_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  hd_sentryHdSentryHostApiClearAllCrashFilesResponse* self = HD_SENTRY_HD_SENTRY_HOST_API_CLEAR_ALL_CRASH_FILES_RESPONSE(g_object_new(hd_sentry_hd_sentry_host_api_clear_all_crash_files_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _hd_sentryHdSentryHostApi {
  GObject parent_instance;

  const hd_sentryHdSentryHostApiVTable* vtable;
  gpointer user_data;
  GDestroyNotify user_data_free_func;
};

G_DEFINE_TYPE(hd_sentryHdSentryHostApi, hd_sentry_hd_sentry_host_api, G_TYPE_OBJECT)

static void hd_sentry_hd_sentry_host_api_dispose(GObject* object) {
  hd_sentryHdSentryHostApi* self = HD_SENTRY_HD_SENTRY_HOST_API(object);
  if (self->user_data != nullptr) {
    self->user_data_free_func(self->user_data);
  }
  self->user_data = nullptr;
  G_OBJECT_CLASS(hd_sentry_hd_sentry_host_api_parent_class)->dispose(object);
}

static void hd_sentry_hd_sentry_host_api_init(hd_sentryHdSentryHostApi* self) {
}

static void hd_sentry_hd_sentry_host_api_class_init(hd_sentryHdSentryHostApiClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = hd_sentry_hd_sentry_host_api_dispose;
}

static hd_sentryHdSentryHostApi* hd_sentry_hd_sentry_host_api_new(const hd_sentryHdSentryHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func) {
  hd_sentryHdSentryHostApi* self = HD_SENTRY_HD_SENTRY_HOST_API(g_object_new(hd_sentry_hd_sentry_host_api_get_type(), nullptr));
  self->vtable = vtable;
  self->user_data = user_data;
  self->user_data_free_func = user_data_free_func;
  return self;
}

static void hd_sentry_hd_sentry_host_api_initialize_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  hd_sentryHdSentryHostApi* self = HD_SENTRY_HD_SENTRY_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->initialize == nullptr) {
    return;
  }

  g_autoptr(hd_sentryHdSentryHostApiInitializeResponse) response = self->vtable->initialize(self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "HdSentryHostApi", "initialize");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "HdSentryHostApi", "initialize", error->message);
  }
}

static void hd_sentry_hd_sentry_host_api_get_crash_directory_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  hd_sentryHdSentryHostApi* self = HD_SENTRY_HD_SENTRY_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->get_crash_directory == nullptr) {
    return;
  }

  g_autoptr(hd_sentryHdSentryHostApiGetCrashDirectoryResponse) response = self->vtable->get_crash_directory(self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "HdSentryHostApi", "getCrashDirectory");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "HdSentryHostApi", "getCrashDirectory", error->message);
  }
}

static void hd_sentry_hd_sentry_host_api_list_crash_file_names_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  hd_sentryHdSentryHostApi* self = HD_SENTRY_HD_SENTRY_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->list_crash_file_names == nullptr) {
    return;
  }

  g_autoptr(hd_sentryHdSentryHostApiListCrashFileNamesResponse) response = self->vtable->list_crash_file_names(self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "HdSentryHostApi", "listCrashFileNames");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "HdSentryHostApi", "listCrashFileNames", error->message);
  }
}

static void hd_sentry_hd_sentry_host_api_read_crash_file_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  hd_sentryHdSentryHostApi* self = HD_SENTRY_HD_SENTRY_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->read_crash_file == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  const gchar* file_name = fl_value_get_string(value0);
  g_autoptr(hd_sentryHdSentryHostApiReadCrashFileResponse) response = self->vtable->read_crash_file(file_name, self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "HdSentryHostApi", "readCrashFile");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "HdSentryHostApi", "readCrashFile", error->message);
  }
}

static void hd_sentry_hd_sentry_host_api_delete_crash_file_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  hd_sentryHdSentryHostApi* self = HD_SENTRY_HD_SENTRY_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->delete_crash_file == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  const gchar* file_name = fl_value_get_string(value0);
  g_autoptr(hd_sentryHdSentryHostApiDeleteCrashFileResponse) response = self->vtable->delete_crash_file(file_name, self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "HdSentryHostApi", "deleteCrashFile");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "HdSentryHostApi", "deleteCrashFile", error->message);
  }
}

static void hd_sentry_hd_sentry_host_api_clear_all_crash_files_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  hd_sentryHdSentryHostApi* self = HD_SENTRY_HD_SENTRY_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->clear_all_crash_files == nullptr) {
    return;
  }

  g_autoptr(hd_sentryHdSentryHostApiClearAllCrashFilesResponse) response = self->vtable->clear_all_crash_files(self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "HdSentryHostApi", "clearAllCrashFiles");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "HdSentryHostApi", "clearAllCrashFiles", error->message);
  }
}

void hd_sentry_hd_sentry_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const hd_sentryHdSentryHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func) {
  g_autofree gchar* dot_suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");
  g_autoptr(hd_sentryHdSentryHostApi) api_data = hd_sentry_hd_sentry_host_api_new(vtable, user_data, user_data_free_func);

  g_autoptr(hd_sentryMessageCodec) codec = hd_sentry_message_codec_new();
  g_autofree gchar* initialize_channel_name = g_strdup_printf("dev.flutter.pigeon.hd_sentry.HdSentryHostApi.initialize%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) initialize_channel = fl_basic_message_channel_new(messenger, initialize_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(initialize_channel, hd_sentry_hd_sentry_host_api_initialize_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* get_crash_directory_channel_name = g_strdup_printf("dev.flutter.pigeon.hd_sentry.HdSentryHostApi.getCrashDirectory%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) get_crash_directory_channel = fl_basic_message_channel_new(messenger, get_crash_directory_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(get_crash_directory_channel, hd_sentry_hd_sentry_host_api_get_crash_directory_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* list_crash_file_names_channel_name = g_strdup_printf("dev.flutter.pigeon.hd_sentry.HdSentryHostApi.listCrashFileNames%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) list_crash_file_names_channel = fl_basic_message_channel_new(messenger, list_crash_file_names_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(list_crash_file_names_channel, hd_sentry_hd_sentry_host_api_list_crash_file_names_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* read_crash_file_channel_name = g_strdup_printf("dev.flutter.pigeon.hd_sentry.HdSentryHostApi.readCrashFile%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) read_crash_file_channel = fl_basic_message_channel_new(messenger, read_crash_file_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(read_crash_file_channel, hd_sentry_hd_sentry_host_api_read_crash_file_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* delete_crash_file_channel_name = g_strdup_printf("dev.flutter.pigeon.hd_sentry.HdSentryHostApi.deleteCrashFile%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) delete_crash_file_channel = fl_basic_message_channel_new(messenger, delete_crash_file_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(delete_crash_file_channel, hd_sentry_hd_sentry_host_api_delete_crash_file_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* clear_all_crash_files_channel_name = g_strdup_printf("dev.flutter.pigeon.hd_sentry.HdSentryHostApi.clearAllCrashFiles%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) clear_all_crash_files_channel = fl_basic_message_channel_new(messenger, clear_all_crash_files_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(clear_all_crash_files_channel, hd_sentry_hd_sentry_host_api_clear_all_crash_files_cb, g_object_ref(api_data), g_object_unref);
}

void hd_sentry_hd_sentry_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix) {
  g_autofree gchar* dot_suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");

  g_autoptr(hd_sentryMessageCodec) codec = hd_sentry_message_codec_new();
  g_autofree gchar* initialize_channel_name = g_strdup_printf("dev.flutter.pigeon.hd_sentry.HdSentryHostApi.initialize%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) initialize_channel = fl_basic_message_channel_new(messenger, initialize_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(initialize_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* get_crash_directory_channel_name = g_strdup_printf("dev.flutter.pigeon.hd_sentry.HdSentryHostApi.getCrashDirectory%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) get_crash_directory_channel = fl_basic_message_channel_new(messenger, get_crash_directory_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(get_crash_directory_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* list_crash_file_names_channel_name = g_strdup_printf("dev.flutter.pigeon.hd_sentry.HdSentryHostApi.listCrashFileNames%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) list_crash_file_names_channel = fl_basic_message_channel_new(messenger, list_crash_file_names_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(list_crash_file_names_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* read_crash_file_channel_name = g_strdup_printf("dev.flutter.pigeon.hd_sentry.HdSentryHostApi.readCrashFile%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) read_crash_file_channel = fl_basic_message_channel_new(messenger, read_crash_file_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(read_crash_file_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* delete_crash_file_channel_name = g_strdup_printf("dev.flutter.pigeon.hd_sentry.HdSentryHostApi.deleteCrashFile%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) delete_crash_file_channel = fl_basic_message_channel_new(messenger, delete_crash_file_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(delete_crash_file_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* clear_all_crash_files_channel_name = g_strdup_printf("dev.flutter.pigeon.hd_sentry.HdSentryHostApi.clearAllCrashFiles%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) clear_all_crash_files_channel = fl_basic_message_channel_new(messenger, clear_all_crash_files_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(clear_all_crash_files_channel, nullptr, nullptr, nullptr);
}
