// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_

#include <flutter_linux/flutter_linux.h>

G_BEGIN_DECLS

G_DECLARE_FINAL_TYPE(hd_sentryMessageCodec, hd_sentry_message_codec, HD_SENTRY, MESSAGE_CODEC, FlStandardMessageCodec)

G_DECLARE_FINAL_TYPE(hd_sentryHdSentryHostApi, hd_sentry_hd_sentry_host_api, HD_SENTRY, HD_SENTRY_HOST_API, GObject)

G_DECLARE_FINAL_TYPE(hd_sentryHdSentryHostApiInitializeResponse, hd_sentry_hd_sentry_host_api_initialize_response, HD_SENTRY, HD_SENTRY_HOST_API_INITIALIZE_RESPONSE, GObject)

/**
 * hd_sentry_hd_sentry_host_api_initialize_response_new:
 *
 * Creates a new response to HdSentryHostApi.initialize.
 *
 * Returns: a new #hd_sentryHdSentryHostApiInitializeResponse
 */
hd_sentryHdSentryHostApiInitializeResponse* hd_sentry_hd_sentry_host_api_initialize_response_new();

/**
 * hd_sentry_hd_sentry_host_api_initialize_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to HdSentryHostApi.initialize.
 *
 * Returns: a new #hd_sentryHdSentryHostApiInitializeResponse
 */
hd_sentryHdSentryHostApiInitializeResponse* hd_sentry_hd_sentry_host_api_initialize_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(hd_sentryHdSentryHostApiGetCrashDirectoryResponse, hd_sentry_hd_sentry_host_api_get_crash_directory_response, HD_SENTRY, HD_SENTRY_HOST_API_GET_CRASH_DIRECTORY_RESPONSE, GObject)

/**
 * hd_sentry_hd_sentry_host_api_get_crash_directory_response_new:
 *
 * Creates a new response to HdSentryHostApi.getCrashDirectory.
 *
 * Returns: a new #hd_sentryHdSentryHostApiGetCrashDirectoryResponse
 */
hd_sentryHdSentryHostApiGetCrashDirectoryResponse* hd_sentry_hd_sentry_host_api_get_crash_directory_response_new(const gchar* return_value);

/**
 * hd_sentry_hd_sentry_host_api_get_crash_directory_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to HdSentryHostApi.getCrashDirectory.
 *
 * Returns: a new #hd_sentryHdSentryHostApiGetCrashDirectoryResponse
 */
hd_sentryHdSentryHostApiGetCrashDirectoryResponse* hd_sentry_hd_sentry_host_api_get_crash_directory_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(hd_sentryHdSentryHostApiListCrashFileNamesResponse, hd_sentry_hd_sentry_host_api_list_crash_file_names_response, HD_SENTRY, HD_SENTRY_HOST_API_LIST_CRASH_FILE_NAMES_RESPONSE, GObject)

/**
 * hd_sentry_hd_sentry_host_api_list_crash_file_names_response_new:
 *
 * Creates a new response to HdSentryHostApi.listCrashFileNames.
 *
 * Returns: a new #hd_sentryHdSentryHostApiListCrashFileNamesResponse
 */
hd_sentryHdSentryHostApiListCrashFileNamesResponse* hd_sentry_hd_sentry_host_api_list_crash_file_names_response_new(FlValue* return_value);

/**
 * hd_sentry_hd_sentry_host_api_list_crash_file_names_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to HdSentryHostApi.listCrashFileNames.
 *
 * Returns: a new #hd_sentryHdSentryHostApiListCrashFileNamesResponse
 */
hd_sentryHdSentryHostApiListCrashFileNamesResponse* hd_sentry_hd_sentry_host_api_list_crash_file_names_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(hd_sentryHdSentryHostApiReadCrashFileResponse, hd_sentry_hd_sentry_host_api_read_crash_file_response, HD_SENTRY, HD_SENTRY_HOST_API_READ_CRASH_FILE_RESPONSE, GObject)

/**
 * hd_sentry_hd_sentry_host_api_read_crash_file_response_new:
 *
 * Creates a new response to HdSentryHostApi.readCrashFile.
 *
 * Returns: a new #hd_sentryHdSentryHostApiReadCrashFileResponse
 */
hd_sentryHdSentryHostApiReadCrashFileResponse* hd_sentry_hd_sentry_host_api_read_crash_file_response_new(const gchar* return_value);

/**
 * hd_sentry_hd_sentry_host_api_read_crash_file_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to HdSentryHostApi.readCrashFile.
 *
 * Returns: a new #hd_sentryHdSentryHostApiReadCrashFileResponse
 */
hd_sentryHdSentryHostApiReadCrashFileResponse* hd_sentry_hd_sentry_host_api_read_crash_file_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(hd_sentryHdSentryHostApiDeleteCrashFileResponse, hd_sentry_hd_sentry_host_api_delete_crash_file_response, HD_SENTRY, HD_SENTRY_HOST_API_DELETE_CRASH_FILE_RESPONSE, GObject)

/**
 * hd_sentry_hd_sentry_host_api_delete_crash_file_response_new:
 *
 * Creates a new response to HdSentryHostApi.deleteCrashFile.
 *
 * Returns: a new #hd_sentryHdSentryHostApiDeleteCrashFileResponse
 */
hd_sentryHdSentryHostApiDeleteCrashFileResponse* hd_sentry_hd_sentry_host_api_delete_crash_file_response_new(gboolean return_value);

/**
 * hd_sentry_hd_sentry_host_api_delete_crash_file_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to HdSentryHostApi.deleteCrashFile.
 *
 * Returns: a new #hd_sentryHdSentryHostApiDeleteCrashFileResponse
 */
hd_sentryHdSentryHostApiDeleteCrashFileResponse* hd_sentry_hd_sentry_host_api_delete_crash_file_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(hd_sentryHdSentryHostApiClearAllCrashFilesResponse, hd_sentry_hd_sentry_host_api_clear_all_crash_files_response, HD_SENTRY, HD_SENTRY_HOST_API_CLEAR_ALL_CRASH_FILES_RESPONSE, GObject)

/**
 * hd_sentry_hd_sentry_host_api_clear_all_crash_files_response_new:
 *
 * Creates a new response to HdSentryHostApi.clearAllCrashFiles.
 *
 * Returns: a new #hd_sentryHdSentryHostApiClearAllCrashFilesResponse
 */
hd_sentryHdSentryHostApiClearAllCrashFilesResponse* hd_sentry_hd_sentry_host_api_clear_all_crash_files_response_new();

/**
 * hd_sentry_hd_sentry_host_api_clear_all_crash_files_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to HdSentryHostApi.clearAllCrashFiles.
 *
 * Returns: a new #hd_sentryHdSentryHostApiClearAllCrashFilesResponse
 */
hd_sentryHdSentryHostApiClearAllCrashFilesResponse* hd_sentry_hd_sentry_host_api_clear_all_crash_files_response_new_error(const gchar* code, const gchar* message, FlValue* details);

/**
 * hd_sentryHdSentryHostApiVTable:
 *
 * Table of functions exposed by HdSentryHostApi to be implemented by the API provider.
 */
typedef struct {
  hd_sentryHdSentryHostApiInitializeResponse* (*initialize)(gpointer user_data);
  hd_sentryHdSentryHostApiGetCrashDirectoryResponse* (*get_crash_directory)(gpointer user_data);
  hd_sentryHdSentryHostApiListCrashFileNamesResponse* (*list_crash_file_names)(gpointer user_data);
  hd_sentryHdSentryHostApiReadCrashFileResponse* (*read_crash_file)(const gchar* file_name, gpointer user_data);
  hd_sentryHdSentryHostApiDeleteCrashFileResponse* (*delete_crash_file)(const gchar* file_name, gpointer user_data);
  hd_sentryHdSentryHostApiClearAllCrashFilesResponse* (*clear_all_crash_files)(gpointer user_data);
} hd_sentryHdSentryHostApiVTable;

/**
 * hd_sentry_hd_sentry_host_api_set_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 * @vtable: implementations of the methods in this API.
 * @user_data: (closure): user data to pass to the functions in @vtable.
 * @user_data_free_func: (allow-none): a function which gets called to free @user_data, or %NULL.
 *
 * Connects the method handlers in the HdSentryHostApi API.
 */
void hd_sentry_hd_sentry_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const hd_sentryHdSentryHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func);

/**
 * hd_sentry_hd_sentry_host_api_clear_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Clears the method handlers in the HdSentryHostApi API.
 */
void hd_sentry_hd_sentry_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix);

G_END_DECLS

#endif  // PIGEON_MESSAGES_G_H_
